# Generated by Django 4.2.1 on 2023-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='avatar')),
                ('cover_photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='cover_photo')),
                ('discription', models.TextField(blank=True, db_index=True, null=True, verbose_name='discription')),
                ('accessibility', models.CharField(max_length=15, verbose_name='accessibility')),
                ('owner', models.CharField(max_length=64, verbose_name='owner')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'name',
                'ordering': ('name',),
            },
        ),
    ]
