# Generated by Django 4.2.1 on 2023-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='surname')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='username')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'handle_user',
                'verbose_name_plural': 'handle_user',
                'ordering': ('email',),
            },
        ),
    ]
